name: kennady_photo
description: "Kennady Photo AI App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image_gallery_saver_plus: ^3.0.4
  permission_handler: ^11.3.1
  http: ^1.2.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

flutter:
  uses-material-design: true
